name: Test Behat CI

on:
  pull_request:
  workflow_dispatch:
  # Nightly at 00:00 UTC (CircleCI: "0 0 * * *")
  schedule:
    - cron: "0 0 * * *"

jobs:
  test-behat:
    # Skip scheduled runs unless the workflow file is on a branch named 'release'
    if: github.event_name != 'schedule' || github.ref_name == 'release'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/vendor
          key: test-lint-dependencies-{{ checksum "composer.json" }}
          restore-keys: test-lint-dependencies-{{ checksum "composer.json" }}

      - name: Install dependencies
        run: composer install -n --prefer-dist

      - name: Run PHP Lint
        run: composer phpcs

      - name: Generate WP admin password
        run: echo "$(openssl rand -hex 8)" > /tmp/WORDPRESS_ADMIN_PASSWORD

      - name: Export environment (CircleCI -> GHA equivalents)
        run: |
          echo "TERMINUS_ENV=ci-${GITHUB_RUN_NUMBER}" >> "$GITHUB_ENV"
          echo "TERMINUS_SITE=pantheon-hud" >> "$GITHUB_ENV"
          echo "SITE_ENV=pantheon-hud.ci-${GITHUB_RUN_NUMBER}" >> "$GITHUB_ENV"
          echo "WORDPRESS_ADMIN_USERNAME=pantheon" >> "$GITHUB_ENV"
          echo "WORDPRESS_ADMIN_EMAIL=no-reply@getpantheon.com" >> "$GITHUB_ENV"
          echo "WORDPRESS_ADMIN_PASSWORD=$(cat /tmp/WORDPRESS_ADMIN_PASSWORD)" >> "$GITHUB_ENV"

      # Configures SSH to automatically accept new host keys.
      - name: Force SSH to ignore host keys
        run: echo "GIT_SSH_COMMAND=ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" >> $GITHUB_ENV

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SITE_OWNER_SSH_PRIVATE_KEY }}

      - name: Configure Composer GitHub OAuth (optional)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "${GITHUB_TOKEN}" ]; then
            echo "GITHUB_TOKEN missing; assuming unauthenticated build"; exit 0
          fi
          { composer config -g github-oauth.github.com "${GITHUB_TOKEN}"; } &>/dev/null

      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@v1
        with:
          pantheon-machine-token: ${{ secrets.TERMINUS_TOKEN }}

      - name: Validate fixture version
        uses: jazzsequence/action-validate-plugin-version@v1
        with:
          branch: ${{ github.head_ref }}
          dry-run: 'true'

      - name: Behat prepare
        run: ./bin/behat-prepare.sh

      - name: Behat tests (strict)
        run: ./bin/behat-test.sh --strict

      - name: Behat cleanup (always)
        if: always()
        run: ./bin/behat-cleanup.sh
